### ISSUE TITLE
hey questions

### ISSUE THREAD

**Issue by Davidzhu001** [chenhsong/OpenProtocol#1]
does you system support 
![image](https://user-images.githubusercontent.com/9436230/131945230-4eebd336-4583-4fde-b2fb-60e05819f993.png)
![image](https://user-images.githubusercontent.com/9436230/131945253-6a4aff07-bbad-4953-b542-4795bc075884.png)
this one, and how to collect data from them?

**Comment by schungx** [comment]
Yes, certainly.  The CPC 6.0 is networkable.  It is part of the "Ai Series" of controllers.

Just follow the instructions in:

https://chenhsong.github.io/iChen/

Physical wiring can be done as per this diagram: https://chenhsong.github.io/iChen/doc/wiring_specs.png

**Comment by Davidzhu001** [comment]
@schungx do you have any instruction pdf or anything can share. 
Thanks so much for quick response !

best wish

**Comment by schungx** [comment]
Check out the website: https://chenhsong.github.io/iChen/

You'll find all information there.  Most of our clients already can connect based on this.

If you have any more problems, feel free to ask.

**Comment by Davidzhu001** [comment]
sorry for so wordy, my factory recently bought 6 of cpc-6.0 production.
1. do i need a license in order to collect the data from the panel?
2. can we collect from ethernet only? or do we need to transfer from rs232to485torj45?
thanks so much

**Comment by schungx** [comment]
Not a problem at all!

All software is free as per the terms. No licence needed.

The CPC outputs standard RS232 which we suggest you convert to RS485 for more reliable transmissions.  You may also consume the RS232 feed directly; a few clients of ours do that by installing a network adapter card directly on the machine.

**Comment by schungx** [comment]
Just checking back whether you have resolved your problems.

**Comment by Davidzhu001** [comment]
thanks so much for checking, we are still working on it in a slow process. lol i will keep you on updates on it! many thanks

**Comment by schungx** [comment]
OK, closing this for now.  Feel free to open up another issue if you have any more prob.

**Comment by Davidzhu001** [comment]
Where is RS 232 port

**Comment by schungx** [comment]
![image](https://user-images.githubusercontent.com/661318/135018662-6b00bb72-dbbf-465a-8a2d-0c64b8e8f4e1.png)

The S100 connector.

**Comment by Davidzhu001** [comment]
ok thanks! I bought everything from 
![image](https://user-images.githubusercontent.com/9436230/135049934-70841385-5730-43ea-8c24-29c3e81ed2d6.png)
hope everything is working without long stop machine running lol!

**Comment by schungx** [comment]
Let us know.  We'll help you diagnose.  We have clients who did everything himself and works no prob.

**Comment by Davidzhu001** [comment]
@schungx thanks, if everything works fine, i will help to make a doc to thank you guys.!

**Comment by schungx** [comment]
If you haven't bought the 485 Ethernet server yet, you can start with a simple USB-485 adapter (or even directly a USB-232 adapter if your computer is next to the machine).  Those are real cheap and you can simply test the data connection before you spend $$$ on an Ethernet server...

**Comment by Davidzhu001** [comment]
i saw the 485 Ethernet server hub is good for 4 machines. we have 8 machines in one row. and i planed to make the rs485 wire longer so that they can share one server hub. my boss i wish we have a demo to show by oct 15th. so we don't have too much time lol. thanks tho. if the first group works fine. we will find a better way to connect them directly.

**Comment by schungx** [comment]
Great.  No prob.  iChen should work with 8 machines just fine.

Remember that it is sometimes tricky to setup the Ethernet server hub.  Make sure you disable buffering - that's important, because the data connection is timing-dependent.  And if you get no data, then chances are that you got the baud rate wrong, the wires switched, or the wrong mode set on the server.

That's why I suggest trying out with RS232 straight-through first, just to ensure that you can read the data.

**Comment by Davidzhu001** [comment]
@schungx ok, thanks so much, you are the BEST support i have every met during doing iot projects. that's really helpful. save a lot times and lots complaining from machine runners! lol
